spring:
  application:
    name: nivio
  main:
    lazy-initialization: true

github: # add new environment variables
  login: kohsuke
  password: 012345678
  oauth: 4d98173f7c075527cb64878561d1fe70
  jwt: my_jwt_token


