name: Java CI

on:
  workflow_call:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:9.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        working-directory: src/main/app
        run: cypress run