on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
    secrets:
      cypress_key:
        required: false

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          working-directory: src/main/app
        env:
          CYPRESS_RECORD_KEY: ${{ inputs.cypress_key }}