on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
    secrets:
      cypress_key:
        required: false

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:9.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
        env:
          CYPRESS_RECORD_KEY: ${{ inputs.cypress_key }}