on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:9.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        working-directory: src/main/app
        run: cypress run --env url=${{ inputs.url }}