name: CI reuse test

on:
  push:
    tags:
      - '*'
    branches:
      - 245_improve_frontend_tests

jobs:
  cypress_test:
    uses: ./.github/workflows/cypress_test.yml
    with:
      url: https://nivio-demo.herokuapp.com