name: CI reuse test

on:
  push:
    tags:
      - '*'
    branches:
      - 245_improve_frontend_tests

jobs:
  cypress_test:
    uses: dedica/nivio/.github/workflows/cypress_test.yml@8bf86620783b4b77dfaf70611160775a6fb0f293
    with:
      url: https://nivio-demo.herokuapp.com