name: CI reuse test

on:
  push:
    tags:
      - '*'
    branches:
      - 245_improve_frontend_tests

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:9.3.1
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        working-directory: src/main/app
        run: cypress run --env urlhttps://nivio-demo.herokuapp.com

#  cypress_test:
#    uses: dedica/nivio/.github/workflows/cypress_test.yml@main
#    with:
#      url: https://nivio-demo.herokuapp.com